cmake_minimum_required(VERSION 3.10)

add_executable(r1_arm_dex3_grasp_example low_level/r1_arm_dex3_grasp_example.cpp)
target_link_libraries(r1_arm_dex3_grasp_example unitree_sdk2)

add_executable(dex3_hand_position_monitor low_level/dex3_hand_position_monitor.cpp)
target_link_libraries(dex3_hand_position_monitor unitree_sdk2)
